name: ci-postgresql-chart

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    # El tipo de máquina virtual donde se ejecutará el job
    runs-on: ubuntu-latest

    # Los pasos que componen el job
    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Login to Helm Registry
        env:
          HELM_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${HELM_REGISTRY_PASSWORD}" | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
     
      - name: Deploy files
        run: |
          sed -i "s|{{ version }}|${{ github.run_number }}|g" ./postgresql-chart/Chart.yaml
          cat ./postgresql-chart/Chart.yaml
          helm package ./postgresql-chart
 
          helm push ./postgresql-chart-${{ github.run_number }}.tgz oci://registry-1.docker.io/otsugua04
 
